"""
code_generator.py
Converts pixel data into 9 different code output formats.
"""

from typing import List, Tuple

# Minecraft concrete block colours (name → approximate RGB)
_MC_PALETTE = [
    ("white",      (255, 255, 255)),
    ("orange",     (216, 127,  51)),
    ("magenta",    (178,  76, 216)),
    ("light_blue", (102, 153, 216)),
    ("yellow",     (229, 229,  51)),
    ("lime",       (127, 204,  25)),
    ("pink",       (242, 127, 165)),
    ("gray",       ( 76,  76,  76)),
    ("light_gray", (153, 153, 153)),
    ("cyan",       ( 76, 127, 153)),
    ("purple",     (127,  63, 178)),
    ("blue",       ( 51,  76, 178)),
    ("brown",      (102,  76,  51)),
    ("green",      (102, 127,  51)),
    ("red",        (153,  51,  51)),
    ("black",      ( 25,  25,  25)),
]


class CodeGenerator:
    ASCII_CHARS = ["@", "#", "S", "%", "?", "*", "+", ";", ":", ",", ".", " "]

    def generate(self, pixels: List[List[Tuple[int, int, int]]], mode: str) -> str:
        generators = {
            "Python":            self._gen_python,
            "JavaScript Canvas": self._gen_javascript,
            "CSS Pixel Art":     self._gen_css,
            "ASCII Art":         self._gen_ascii,
            "SVG":               self._gen_svg,
            "Pygame":            self._gen_pygame,
            "Unity C#":          self._gen_unity,
            "p5.js":             self._gen_p5js,
            "Minecraft":         self._gen_minecraft,
        }
        if mode not in generators:
            raise ValueError(f"Unknown output mode: '{mode}'")
        return generators[mode](pixels)

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _hex(self, r: int, g: int, b: int) -> str:
        return f"#{r:02x}{g:02x}{b:02x}"

    def _brightness(self, r: int, g: int, b: int) -> int:
        return int(0.299 * r + 0.587 * g + 0.114 * b)

    def _nearest_mc(self, r: int, g: int, b: int) -> str:
        best, best_d = "white", float("inf")
        for name, (cr, cg, cb) in _MC_PALETTE:
            d = (r - cr) ** 2 + (g - cg) ** 2 + (b - cb) ** 2
            if d < best_d:
                best, best_d = name, d
        return best

    # ── Generators ───────────────────────────────────────────────────────────

    def _gen_python(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "# Generated by Image → Pixel Code Generator",
            "import tkinter as tk",
            "",
            "def draw_image(canvas):",
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                lines.append(
                    f"    canvas.create_rectangle({x},{y},{x+1},{y+1},"
                    f"fill='{self._hex(r,g,b)}',outline='')"
                )
        lines += [
            "",
            "if __name__ == '__main__':",
            f"    root = tk.Tk()",
            f"    canvas = tk.Canvas(root, width={w}, height={h}, bd=0, highlightthickness=0)",
            "    canvas.pack()",
            "    draw_image(canvas)",
            "    root.mainloop()",
        ]
        return "\n".join(lines)

    def _gen_javascript(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "// Generated by Image → Pixel Code Generator",
            "(function () {",
            f"  const canvas = document.createElement('canvas');",
            f"  canvas.width = {w}; canvas.height = {h};",
            "  document.body.appendChild(canvas);",
            "  const ctx = canvas.getContext('2d');",
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                lines.append(f'  ctx.fillStyle="rgb({r},{g},{b})";ctx.fillRect({x},{y},1,1);')
        lines.append("})();")
        return "\n".join(lines)

    def _gen_css(self, pixels):
        shadows = []
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                shadows.append(f"    {x+1}px {y+1}px 0 {self._hex(r,g,b)}")
        return (
            "/* Generated by Image → Pixel Code Generator */\n"
            "/* Apply class 'pixel-art' to a 1×1 <div> */\n"
            ".pixel-art {\n  display:block; width:1px; height:1px;\n"
            "  box-shadow:\n" + ",\n".join(shadows) + ";\n}"
        )

    def _gen_ascii(self, pixels):
        last = len(self.ASCII_CHARS) - 1
        rows = []
        for row in pixels:
            rows.append("".join(
                self.ASCII_CHARS[int(self._brightness(r, g, b) / 255 * last)]
                for r, g, b in row
            ))
        return "# Generated by Image → Pixel Code Generator\n\n" + "\n".join(rows)

    def _gen_svg(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "<!-- Generated by Image → Pixel Code Generator -->",
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" shape-rendering="crispEdges">',
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                lines.append(f'  <rect x="{x}" y="{y}" width="1" height="1" fill="{self._hex(r,g,b)}"/>')
        lines.append("</svg>")
        return "\n".join(lines)

    def _gen_pygame(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "# Generated by Image → Pixel Code Generator",
            "import pygame",
            "pygame.init()",
            f"screen = pygame.display.set_mode(({w}, {h}))",
            "pygame.display.set_caption('Pixel Image')",
            "screen.fill((0, 0, 0))",
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                lines.append(f"pygame.draw.rect(screen, ({r},{g},{b}), ({x},{y},1,1))")
        lines += [
            "pygame.display.flip()",
            "running = True",
            "while running:",
            "    for e in pygame.event.get():",
            "        if e.type == pygame.QUIT:",
            "            running = False",
            "pygame.quit()",
        ]
        return "\n".join(lines)

    def _gen_unity(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "// Generated by Image → Pixel Code Generator",
            "// Attach to a GameObject with a Renderer component",
            "using UnityEngine;",
            "",
            "public class PixelImage : MonoBehaviour {",
            "    void Start() {",
            f"        Texture2D tex = new Texture2D({w}, {h});",
            "        tex.filterMode = FilterMode.Point;",
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                rf, gf, bf = round(r/255, 4), round(g/255, 4), round(b/255, 4)
                uy = h - 1 - y  # Unity Y is flipped
                lines.append(f"        tex.SetPixel({x},{uy},new Color({rf}f,{gf}f,{bf}f));")
        lines += [
            "        tex.Apply();",
            "        GetComponent<Renderer>().material.mainTexture = tex;",
            "    }",
            "}",
        ]
        return "\n".join(lines)

    def _gen_p5js(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "// Generated by Image → Pixel Code Generator",
            "function setup() {",
            f"  createCanvas({w}, {h});",
            "  noStroke();",
            "  drawPixels();",
            "  noLoop();",
            "}",
            "",
            "function drawPixels() {",
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                lines.append(f"  fill({r},{g},{b}); rect({x},{y},1,1);")
        lines += ["}", "", "function draw() {}"]
        return "\n".join(lines)

    def _gen_minecraft(self, pixels):
        h = len(pixels)
        w = len(pixels[0]) if pixels else 0
        lines = [
            "# Generated by Image → Pixel Code Generator",
            f"# Minecraft /setblock commands — image: {w}×{h} blocks",
            "# Place this on the XZ plane at Y=64",
            "",
        ]
        for y, row in enumerate(pixels):
            for x, (r, g, b) in enumerate(row):
                block = self._nearest_mc(r, g, b)
                lines.append(f"/setblock {x} 64 {y} minecraft:{block}_concrete")
        return "\n".join(lines)
